import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import type { Metadata } from "next";
import { Genos } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

config.autoAddCss = false;

const michroma = Genos({
    variable: "--font-microma",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700", "800"]
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <script
                    crossOrigin="anonymous"
                    src="//unpkg.com/react-scan/dist/auto.global.js"
                />
            </head>
            <body
                className={`${michroma.variable} antialiased bg-trmnl`}
                suppressHydrationWarning
            >
                {children}
            </body>
        </html>
    );
}
